title: "NS4NLP: Neuro-Symbolic Modeling for NLP"
urltitle: "NS4NLP Tutorial at COLING 2022"
email: ns4nlp-coling@googlegroups.com
description: NS4NLP Coling 2022 Tutorial
keywords: coling, tutorial, ns4nlp, neuro-symbolic, neural-symbolic, nlp, language, representation, learning, symbol, symbols



baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
